# Generated by Django 6.1 on 2026-08-28 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ชื่อหมวดหมู่')),
                ('description', models.TextField(blank=True, null=True, verbose_name='รายละเอียดหมวดหมู่')),
                ('icon', models.CharField(default='package', max_length=50, verbose_name='ชื่อไอคอน (Lucide Icon)')),
            ],
            options={
                'verbose_name': 'หมวดหมู่พัสดุ',
                'verbose_name_plural': 'หมวดหมู่พัสดุ',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='รหัสพัสดุ/ครุภัณฑ์')),
                ('name', models.CharField(max_length=200, verbose_name='ชื่อพัสดุ/ครุภัณฑ์')),
                ('description', models.TextField(blank=True, null=True, verbose_name='รายละเอียดและสเปกพัสดุ')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='ลิงก์รูปภาพพัสดุ')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='ตำแหน่งชั้นวาง (Position Map)')),
                ('total_quantity', models.PositiveIntegerField(default=1, verbose_name='จำนวนทั้งหมด')),
                ('available_quantity', models.PositiveIntegerField(default=1, verbose_name='จำนวนพร้อมใช้งาน')),
                ('is_active', models.BooleanField(default=True, verbose_name='สถานะพร้อมให้บริการ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่เพิ่มพัสดุ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='อัปเดตล่าสุด')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='catalog.category', verbose_name='หมวดหมู่')),
            ],
            options={
                'verbose_name': 'รายการพัสดุ/ครุภัณฑ์',
                'verbose_name_plural': 'รายการพัสดุ/ครุภัณฑ์',
                'ordering': ['-created_at'],
            },
        ),
    ]
