# Generated by Django 6.1 on 2026-08-28 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='items/', verbose_name='อัปโหลดรูปภาพพัสดุ'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='หรือลิงก์รูปภาพ (Image URL)'),
        ),
    ]
