# Generated by Django 6.1 on 2026-08-28 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_item_image_alter_item_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image_url',
        ),
    ]
