# Generated by Django 6.1 on 2026-08-28 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_item_image_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-created_at'], 'verbose_name': 'รายการสิ่งของ', 'verbose_name_plural': 'รายการสิ่งของทั้งหมด'},
        ),
        migrations.AddField(
            model_name='item',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='หรือลิงก์รูปภาพ (Image URL)'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('MATERIAL', '📦 วัสดุ (เบิกแล้วหมดไป)'), ('EQUIPMENT', '🎥 ครุภัณฑ์ (ยืมแล้วต้องนำมาคืน)')], default='EQUIPMENT', max_length=20, verbose_name='ประเภทสิ่งของ'),
        ),
        migrations.AddField(
            model_name='item',
            name='max_borrow_days',
            field=models.PositiveIntegerField(default=7, verbose_name='จำนวนวันยืมสูงสุด (สำหรับครุภัณฑ์)'),
        ),
        migrations.AddField(
            model_name='item',
            name='unit',
            field=models.CharField(default='ชิ้น', max_length=30, verbose_name='หน่วยนับ (เช่น ชิ้น, เครื่อง, ชุด, กล่อง)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='catalog.category', verbose_name='หมวดหมู่'),
        ),
        migrations.AlterField(
            model_name='item',
            name='total_quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='จำนวนทั้งหมดในคลัง'),
        ),
        migrations.CreateModel(
            name='AssetTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_code', models.CharField(max_length=100, unique=True, verbose_name='รหัส Asset Tag รายชิ้น (เช่น UBU-EQ-001)')),
                ('status', models.CharField(choices=[('AVAILABLE', 'พร้อมให้ยืม'), ('BORROWED', 'กำลังถูกยืม'), ('DAMAGED', 'ครุภัณฑ์เสียหาย/ชำรุด'), ('REPAIRING', 'กำลังส่งซ่อม'), ('RETIRED', 'ปลดระวาง/เลิกใช้งาน')], default='AVAILABLE', max_length=20, verbose_name='สถานะรายชิ้น')),
                ('note', models.TextField(blank=True, null=True, verbose_name='หมายเหตุสภาพครุภัณฑ์')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่ลงทะเบียนชิ้นงาน')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_tags', to='catalog.item', verbose_name='ครุภัณฑ์หลัก')),
            ],
            options={
                'verbose_name': 'รหัสครุภัณฑ์รายชิ้น (Asset Tag)',
                'verbose_name_plural': 'รหัสครุภัณฑ์รายชิ้น (Asset Tags)',
                'ordering': ['asset_code'],
            },
        ),
    ]
