# Generated by Django 6.1 on 2026-08-28 02:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('STUDENT', '🎓 นักศึกษา (Student)'), ('STAFF', '👷 เจ้าหน้าที่ (Staff)'), ('ADMIN', '👑 ผู้ดูแลระบบ (Admin)')], default='STUDENT', max_length=20, verbose_name='บทบาทหลัก')),
                ('role_override', models.CharField(blank=True, choices=[('STUDENT', '🎓 นักศึกษา (Student)'), ('STAFF', '👷 เจ้าหน้าที่ (Staff)'), ('ADMIN', '👑 ผู้ดูแลระบบ (Admin)')], max_length=20, null=True, verbose_name='บทบาทสวมสิทธิ์ (Role Override)')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='เบอร์โทรศัพท์ติดต่อ')),
                ('faculty', models.CharField(blank=True, max_length=100, null=True, verbose_name='คณะ/หน่วยงาน')),
                ('department', models.CharField(blank=True, max_length=100, null=True, verbose_name='ภาควิชา/สาขา')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='ถูกระงับสิทธิ์ใช้งาน')),
                ('block_reason', models.TextField(blank=True, null=True, verbose_name='เหตุผลที่ถูกระงับสิทธิ์')),
                ('first_login', models.DateTimeField(auto_now_add=True, verbose_name='เข้าสู่ระบบครั้งแรก')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='อัปเดตล่าสุด')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
