# Generated by Django 6.1 on 2026-08-28 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'นักศึกษา (Student)'), ('STAFF', 'เจ้าหน้าที่ (Staff)'), ('ADMIN', 'ผู้ดูแลระบบ (Admin)')], default='STUDENT', max_length=20, verbose_name='บทบาทหลัก'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role_override',
            field=models.CharField(blank=True, choices=[('STUDENT', 'นักศึกษา (Student)'), ('STAFF', 'เจ้าหน้าที่ (Staff)'), ('ADMIN', 'ผู้ดูแลระบบ (Admin)')], max_length=20, null=True, verbose_name='บทบาทสวมสิทธิ์ (Role Override)'),
        ),
    ]
